version: '3.7'

services:
    nginx:
        image: nginx:latest
        container_name: demo-slim-api
        ports:
            - "8081:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - php-fpm

    php-fpm:
        build: ./docker/php
        container_name: demo-slim-api-php
        links:
            - mysql
        environment:
            - PHP_FPM_ENABLE=1
            - PHP_FPM_SERVER_ADDR=php
            - PHP_FPM_SERVER_PORT=9000
            - PHP_FPM_TIMEOUT=${HTTPD_TIMEOUT_TO_PHP_FPM:-180}
            - DB_HOST=mysql
            - DB_NAME=demo_api
            - DB_USER=root
            - DB_PASS=
            - DB_PORT=3306

        volumes:
            - ./:/var/www/html

    mysql:
        container_name: demo-slim-api-mysql
        image: mysql:5.7
        ports:
            - 33060:3306
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: demo_api
            MYSQL_USER: root
            MYSQL_PASSWORD:
            MYSQL_ROOT_PASSWORD:
        volumes:
            - my-data:/var/lib/mysql

    tests:
        image: "lehrermarktplatz/php-dev-test:latest"
        command: [ "-s", "basic" ]
        environment:
            APP_HOST: "demo-slim-api"
            APP_PORT: "80"

volumes:
    my-data:
